services:
  - type: web
    name: puppeteer-zapier
    runtime: node
    buildCommand: ./render-build.sh && npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20