services:
  - type: web
    name: puppeteer-zapier
    runtime: node
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium && \
      npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
